### ISSUE TITLE
Options to disable showInfoPopup(index)

### ISSUE THREAD

**Issue by WenLonG12345** [furkanaskin/ClickablePieChart#9]
Thanks for this great library and all the hardwork from constributor! <3

However, Is there any options to disable `showInfoPopup(index)`? 
`showInfoPopup(index)` seems to trigger immediately with the click action. 

![image](https://user-images.githubusercontent.com/39330565/127626978-3cb3e832-12e7-4536-a8d1-448381a60caf.png)

**Comment by furkanaskin** [comment]
Thanks for your thoughts! :heart_eyes:

Basically there are some ways of hiding the popup. I.e. if you want to permanently hide popupview you can use showPopup=false attribute, in the other hand when popup comes out and if user clicks outside of the popup, popup will be dismissed. Also i updated library version 1.0.9 and added dismissPopup function for dismissing the popupview whenever you want.(https://github.com/furkanaskin/ClickablePieChart/commit/2142be96aa880fbea0c509a1458416993c6bcd22)

**Comment by WenLonG12345** [comment]
Wow, thanks! For my usage is only to display piechart. Great works tho :)

**Comment by winnerawan** [comment]
click doesnt work when popUp disable
